### ISSUE TITLE
Java does nothing

### ISSUE THREAD

**Issue by shinkintoad** [NTBeta/Untitled_GaMe#2]
Wow lmao a comment. How cool, great game!

**Comment by NTBeta** [comment]
It might be deleted, might not. I’m still debating.

**Comment by shinkintoad** [comment]
The Java port? Or the game itself?

**Comment by shinkintoad** [comment]
Lol.

# ~~ Shinkin (Shinny)
 ~ Beginner programmer and Reverse Engineer. 
  ~ Discord: Shinkin#9694 ; Twitter: shinkintele
